server:
  port: 8079
spring:
  #mysql 开发环境
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dcrep?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: yanghui.123456

  #mysql 运行环境
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://81.70.152.49:3309/dcrep?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#    username: root
#    password: yanghui.123456

  # redis 开发环境
  redis:
    host: 127.0.0.1
    port: 6379
    password: yanghui.123456
    database: 0
    timeout: 3000
  # 运行环境
#  redis:
#    host: 127.0.0.1
#    port: 6380
#    password: yanghui.123456
#    database: 0
#    timeout: 3000
  #返回时间
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  mvc:
    format:
      date: yyyy-MM-dd

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.datasupermacy.entity

#showSql
logging:
  level:
    com:
      example:
#限制文件大小
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
